### ISSUE TITLE
Graphical implementation of this PAM module (GNOME)

### ISSUE THREAD

**Issue by tanguynicolas** [ICS-MU/pam_oauth2_device#32]
Hello,

This PAM module seems to work perfectly for authentication via an SSH connection.

As part of a university study project, I would like to use this project for classic authentication via the graphical interface (GNOME in my case). Can you confirm that this is not currently supported in graphical mode?

Could you give me some pointers on how I could use your module to achieve this? I've already thought of several solutions, but I'd like your opinion. Also, in your opinion, would I necessarily need to modify the module itself?

Thanks for your help and your code.

**Comment by tauceti2** [comment]
Dear Tanguy,

GUI is not supported by the module and we haven't done any work to this direction, so not much advice from our side. Feel free to provide PR.

Best regards,

Michal P.
-- 
Michal Prochazka // ***@***.***

Institute of Computer Science
Masaryk University
Botanicka 68a, 60200 Brno, CZ

CESNET z.s.p.o.
Zikova 4, 16200 Prague 6, CZ

**Comment by tanguynicolas** [comment]
For posterity: we were able to adapt this module by creating .png for QR and use it with lightdm and Nody Greeter to create the theme. It work good. We've used Keycloak to support OAuth device flow.
